### ISSUE TITLE
[Suggestion]: shortcuts to localized sites? 

### ISSUE THREAD

**Issue by Huxpro** [reactjs/react.dev#6761] opened 2024-04-17 13:28 UTC
### Summary

Adding a shortcut somewhere to make localized sites more accessible.

### Details

The legacy site features a link to all localizations, which has been really helpful for users seeking content in their own language.

<img width="183" alt="image" src="https://github.com/reactjs/react.dev/assets/5563315/27c404ec-5b56-495e-8246-3ca3305536a4">

Other frameworks, like Vue, offer similar shortcuts to localized sites, serving as great examples of this practice.

<img width="355" alt="image" src="https://github.com/reactjs/react.dev/assets/5563315/3c832dbe-296f-4389-b647-132c5c51e340">

This may also boost our translators’ morale by giving their work greater visibility within the community.

What do you all think? Where should we place this, and in what form? Personally, I like Vue's dropdown menu approach where the translated content is just a click away. But the drawback is that it can only display a limited number of translations.

**Comment by smikitky** [comment] 2024-04-30 15:20
We have had a working PR for adding this for a long time.

- #6382

Unfortunately, the React team doesn't seem willing to address this "accessibility issue" seriously... It affects the majority of React developers worldwide.

**Comment by rickhanlonii** [comment] 2024-05-01 13:17
For context, we haven't shipped this yet because when the new site was launched the translations weren't complete. I think there are multiple translations now that are complete so we can add this now.

Closing as dupe of: https://github.com/reactjs/react.dev/issues/5994

**Closed by rickhanlonii** 2024-05-01 13:17 UTC
Labels: type: documentation, localization
