### ISSUE TITLE
broken Link !

### ISSUE THREAD

**Issue by unclepacky** [reactjs/react.dev#6566] opened 2024-01-21 16:45 UTC
following the link : https://react.dev/docs/forms#handling-multiple-submit-buttons 
leads to not found page.
This link is present in 
https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations
See the [React <form> docs](https://react.dev/docs/forms#handling-multiple-submit-buttons)

**Comment by pwbriggs** [comment] 2024-01-22 06:26
Hey there, @unclepacky! 👋

Thanks for reporting this issue! This looks like an issue on Next.js' end, so I've opened an issue on their repo: vercel/next.js#60953.

Because the issue is now on the other repo, do you mind closing this issue? Thanks!

**Closed** 2024-01-22 09:16 UTC

**Comment by unclepacky** [comment] 2024-01-22 09:18
Closed

 

Best regards

Claude Aoun
