### ISSUE TITLE
No non-legacy page for Error Decoder

### ISSUE THREAD

**Issue by martincostello** [reactjs/react.dev#6014] opened 2023-05-09 14:39 UTC
If one follows a link for a React error in a website, you are directed to the [legacy react documentation](https://legacy.reactjs.org/docs/error-decoder.html/).

![image](https://github.com/reactjs/react.dev/assets/1439341/346abbf3-ec6b-4582-93e3-320aa4226be5)

There doesn't _appear_ to be a non-legacy equivalent of this page. It would make sense for developers following these error messages from the browser console to a non-legacy page.

When/if there is one, then the URL [here](https://github.com/facebook/react/blob/7ac5e9a602347f3b7d26c60a549c483d3bc88bbf/packages/shared/formatProdErrorMessage.js#L14) should be updated to point to it.

**Comment by rickhanlonii** [comment] 2023-08-11 03:29
Yeah, nice catch. Dupe of https://github.com/reactjs/react.dev/issues/5572 let's track it there.

**Closed by rickhanlonii** 2023-08-11 03:29 UTC
