### ISSUE TITLE
Add RSS feed for Blog

### ISSUE THREAD

**Issue by rubanero14** [reactjs/react.dev#5723] opened 2023-03-18 06:04 UTC
Current link is defunct, please add new RSS feed link for React blogs #5700

**Comment by gaearon** [comment] 2023-03-18 20:14
That's planned but a bit further out. We have some refactoring to do first.

**Comment by LiorAgami** [comment] 2023-03-19 12:48
Can I help with the refactor?

**Comment by 0529bill** [comment] 2023-03-30 02:41
@rubanero14 one alternative is to add React's Twitter page to the RSS reader since all the blogs will be posted on React Twitter account as well!

**Comment by stof** [comment] 2024-01-13 14:32
@gaearon is there any progress regarding restoring the RSS feed ?

**Comment by rickhanlonii** [comment] 2024-01-13 18:14
Closing as dupe of https://github.com/reactjs/react.dev/issues/5700, let's trace there.

**Closed by rickhanlonii** 2024-01-13 18:14 UTC

**Comment by rickhanlonii** [comment] 2024-04-26 16:08
RSS Feed is available here: https://react.dev/rss.xml
