### ISSUE TITLE
No scrollbar, cannot scroll sidebar

### ISSUE THREAD

**Issue by joshribakoff** [reactjs/react.dev#3171] opened 2020-08-04 17:14 UTC
![Screen Shot 2020-08-04 at 10 13 25 AM](https://user-images.githubusercontent.com/4021306/89323853-3511e080-d63b-11ea-854b-f97f09f54840.png)

**Comment by rimildeyjsr** [comment] 2020-08-05 06:56
@rickhanlonii - can I work on a PR for this, if this needs to be fixed?

**Comment by sijusamson** [comment] 2020-08-06 05:17
@joshribakoff Is this a system specific issue ? As I am able to scroll sidebar. So I guess there is no need for an extra scroll bar. 

Looking forward to hear from you !

**Comment by rickhanlonii** [comment] 2020-08-14 01:52
Yeah @rimildeyjsr! I'm not sure what the issue is though, @joshribakoff can you explain?

**Comment by ShivamYadav-Coding** [comment] 2021-06-02 14:35
If any one have this problem then just try to use your touchpad gestures or mouse scroll wheel over sidebar. I think you might not using it and searching for a scrollbar.

**Comment by MubashirWaheed** [comment] 2023-09-26 14:06
In the `https://react.dev/reference/react` section I am unable to scroll

https://github.com/reactjs/react.dev/assets/41460586/5e1434ac-39a8-4442-ade0-68dd04ea0235

**Comment by raahul131** [comment] 2023-11-23 04:10
Can I work in this issue, I have experience on working on this type of issues previously.

**Comment by ArchitGajjar** [comment] 2023-12-29 07:13
Hi @joshribakoff is this issue still open or closed ? can you please assigned to me ?

**Closed** 2024-02-10 19:38 UTC
Labels: good first issue
