### ISSUE TITLE
A Demo In "Concurrent UI Patterns" still got warning in CodeSandbox's console.

### ISSUE THREAD

**Issue by wangpeng1994** [reactjs/react.dev#3066] opened 2020-06-27 05:00 UTC
> Warning: App triggered a user-blocking update that suspended.
> The fix is to split the update into multiple parts: a user-blocking update to provide immediate feedback, and another update that triggers the bulk of the changes.
> Refer to the documentation for useTransition to learn how to implement this pattern.

> So the correct fix is to put setQuery (which doesn’t suspend) outside the transition, but setResource (which will suspend) inside of it.

[Try it on CodeSandbox
](https://codesandbox.io/s/lively-smoke-fdf93)
> With this change, it works as expected. We can type into the input immediately, and the translation later “catches up” to what we have typed.

**Comment by rickhanlonii** [comment] 2020-07-08 01:49
Nice find, confirmed.

**Comment by rickhanlonii** [comment] 2024-01-11 16:45
Closing since we're not updating the old site any more and this doc is deprecated.

**Closed by rickhanlonii** 2024-01-11 16:45 UTC
Labels: bug: confirmed, type: example
