### ISSUE TITLE
when one of the navs items is clicked it open the dropdown but when clicked again it does not close the dropdown.

### ISSUE THREAD

**Issue by AliSinaYOusofi** [reactjs/react.dev#6517] opened 2023-12-25 10:35 UTC

**Comment by lennygir** [comment] 2023-12-25 21:39
I think the main problem is that when you click on a drop-down button, it redirects you to the corresponding page (and opens the drop-down list). If you click again, you should be redirected to another page for the dropdown to close, but which one? I think this would give unexpected behavior to users.

**Comment by AliSinaYOusofi** [comment] 2023-12-26 11:06
@lennygir I think it is better to close the drop down when clicked the second time be cause it makes more sense.

**Comment by McDonaldMusimwa** [comment] 2024-01-02 12:11
@AliSinaYOusofi and @lennygir  has anyone been assigned to this issue? if not I would like to work on it.

**Comment by AliSinaYOusofi** [comment] 2024-01-02 18:57
@lennygir  I don't think so

**Comment by rickhanlonii** [comment] 2024-01-06 21:10
Yeah, this is intentional because it "expands" for the page you're viewing. If the page didn't navigate on click, it would make sense to collapse it. That UX might be weird to some, but the alternative could also be weird for others.

**Closed by rickhanlonii** 2024-01-06 21:10 UTC
