### ISSUE TITLE
`react-reconciler`: README host config links resolve to 404

### ISSUE THREAD

**Issue by aidenybai** [reactjs/react.dev#5849] opened 2023-03-31 09:01 UTC
The host config links for React DOM resolve to 404: https://www.npmjs.com/package/react-reconciler

**Comment by aidenybai** [comment] 2023-03-31 09:02
I'm not sure whether this goes under this repo as a docs issue or react as a bug

**Comment by ArslanYM** [comment] 2023-03-31 14:20
Its working

**Comment by aidenybai** [comment] 2023-03-31 19:26
correction* just for React DOM

**Comment by gaearon** [comment] 2023-03-31 20:28
Can you please be more specific? Which link is 404?

**Comment by aidenybai** [comment] 2023-03-31 22:10
Sorry about that, here is the steps for reproduction:

1. Go to [npmjs.com/package/react-reconciler](https://www.npmjs.com/package/react-reconciler)
2. Go under the Practical Examples section and look for host configs:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/38025074/229241609-5a5deecf-6eff-4682-8d15-8286213490eb.png">
3. Click on the `host config` link for React DOM (Broken link: https://github.com/facebook/react/blob/main/packages/react-dom/src/client/ReactDOMHostConfig.js)

**Comment by ArslanYM** [comment] 2023-04-01 04:35
Can i work on this ?

**Comment by ArslanYM** [comment] 2023-04-01 04:35
please

**Comment by ArslanYM** [comment] 2023-04-01 14:38
@aidenybai What should this link be pointing to? Since the current link doesnt exist

**Comment by aidenybai** [comment] 2023-04-02 00:44
I'm not actually sure... I haven't been able to find the actual host config for React DOM myself

**Comment by gaearon** [comment] 2023-04-02 19:47
It's in the React repo: https://github.com/facebook/react/blob/main/packages/react-dom-bindings/src/client/ReactDOMHostConfig.js. You can similarly search for other files by name. If you'd like, please send a fix to the README.md in `packages/react-reconciler/` in the React repo.

**Comment by harish-sethuraman** [comment] 2023-04-04 09:27
It has correct link in the readme for react-dom host config?  The readme in npm registry doesnt seem to reflect it? 

https://github.com/facebook/react/blob/4a1cc2ddd035f5c269e82ab6f7686e2e60d3b3ea/packages/react-reconciler/README.md?plain=1#L61

**Comment by roy9495** [comment] 2023-04-14 21:01
the issue is fixed in this pr https://github.com/facebook/react/pull/26592

**Comment by roy9495** [comment] 2023-04-14 21:12
> the issue is fixed in this pr [facebook/react#26592](https://github.com/facebook/react/pull/26592)

The updated Readme.md https://github.com/facebook/react/tree/main/packages/react-reconciler

**Closed** 2023-04-14 21:18 UTC

**Comment by aidenybai** [comment] 2023-04-14 21:56
awesome, great work @roy9495

**Comment by roy9495** [comment] 2023-04-15 07:03
> awesome, great work @roy9495

Thank You
