### ISSUE TITLE
Page 'Not Found' Error

### ISSUE THREAD

**Issue by AdarshSahani003** [reactjs/react.dev#7112] opened 2024-08-17 10:29 UTC
The page "https://react.dev/docs/reconciliation.html" is not found.

![Not_found_error](https://github.com/user-attachments/assets/f7e1932f-d936-41ec-abca-f887078c4cba)

**Comment by harish-sethuraman** [comment] 2024-08-17 16:18
Can you mention from where you landed to that page?

**Comment by eric-net** [comment] 2024-08-18 09:33
> The page "https://react.dev/docs/reconciliation.html" is not found.
> 
> ![Not_found_error](https://private-user-images.githubusercontent.com/118045921/358839891-f7e1932f-d936-41ec-abca-f887078c4cba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzM4NTUsIm5iZiI6MTcyMzk3MzU1NSwicGF0aCI6Ii8xMTgwNDU5MjEvMzU4ODM5ODkxLWY3ZTE5MzJmLWQ5MzYtNDFlYy1hYmNhLWY4ODcwNzhjNGNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwOTMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTYxNTEyNThkNGNkMTJhZTU0NTg5ZTExYzY4NjA4ZWY2OTQ1NTJiMGMwMDc5YTEzODI0MThjMjVhYzA2ODY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3fZeOh7ofsI-XIaiHIiYUrQQwno2xKieao_uih12Am4)

what is the origin from this web page?

**Comment by AdarshSahani003** [comment] 2024-08-21 07:14
> Can you mention from where you landed to that page?

[https://github.com/acdlite/react-fiber-architecture](url)

**Comment by BartoszKlonowski** [comment] 2024-08-26 13:06
I believe this is a duplicate of #6913, so I will close it.
CC: @harish-sethuraman
Thank you!

**Closed by BartoszKlonowski** 2024-08-26 13:06 UTC
Labels: duplicate
