### ISSUE TITLE
React.dev website not loading on all my browsers and devices 

### ISSUE THREAD

**Issue by aiKhalil08** [reactjs/react.dev#6907] opened 2024-05-23 22:00 UTC
### Summary

When i try to open the react.dev url in my browser, i get an error after some time that the page could not be reached. This is the case in all brosers accross all my devices. It has been like this for some weeks now
![Screenshot from 2024-05-23 22-58-58](https://github.com/reactjs/react.dev/assets/77899538/ed6dfebf-9b35-48fa-b968-74022c78573f)

### Page

https://react.dev

**Comment by PrimoCrypt** [comment] 2024-06-13 05:53
Same here i tried accessing it today and I am getting a similar error

![Screenshot from 2024-06-13 06-52-59](https://github.com/reactjs/react.dev/assets/104681010/e5cea810-7187-4860-8d5a-f9a19f5243a2)

**Comment by rickhanlonii** [comment] 2024-06-14 15:51
Dupe of https://github.com/reactjs/react.dev/issues/6732

**Closed by rickhanlonii** 2024-06-14 15:51 UTC
Labels: bug: unconfirmed
