### ISSUE TITLE
[Bug]: the scrollbar on the sidebar - not being clickable with the mouse

### ISSUE THREAD

**Issue by saranyasri-s** [reactjs/react.dev#6604] opened 2024-02-03 11:53 UTC
### Summary

The scrollbar on the sidebar,  is not clickable with the mouse. This issue is affecting the user experience when trying to navigate through the sidebar content.

Steps to Reproduce:

Open the React dev repository on the latest version (insert version number).
Navigate to the sidebar.
Attempt to click and drag the scrollbar using the mouse.
Note that the scrollbar is not responsive to mouse clicks.

Expected Behavior:

The scrollbar on the sidebar should be clickable, allowing users to scroll through the content using the mouse.

Actual Behavior:

The scrollbar is not responding to mouse clicks, making it impossible to scroll through the sidebar content using the mouse.

https://github.com/reactjs/react.dev/assets/87513003/8060ce9c-831c-4b88-bcf3-c1723e43a65e

 

### Page

https://react.dev/learn/describing-the-ui

**Comment by pwbriggs** [comment] 2024-02-04 07:44
Hey there @saranyasri-s! 👋

This appears to be a duplicate of #5805, #6220, #6230, and #6469. If this is indeed a duplicate, please mark this issue as closed. Otherwise, please explain how the bug you're reporting it different from the ones I've mentioned.

Thanks!

**Closed** 2024-02-04 07:50 UTC
Labels: bug: unconfirmed

**Comment by saranyasri-s** [comment] 2024-02-04 07:53
As this issue is already being reported, iam closing this. I didn’t notice it while reporting, sorry for the inconvenience. Thank you for valuable time and comments
